# CloudFormation addon to configure ALB idle timeout for SSE connections
# This is required because AWS Copilot doesn't expose ALB idle timeout in the manifest
# Reference: https://github.com/aws/copilot-cli/discussions/3632

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service is being deployed to.
  Name:
    Type: String
    Description: The name of the service.

Resources:
  # Lambda function to modify ALB attributes
  ALBTimeoutFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Timeout: 60
      Role: !GetAtt ALBTimeoutFunctionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os
          
          def handler(event, context):
              print(f"Event: {event}")
              
              try:
                  if event['RequestType'] in ['Create', 'Update']:
                      elb = boto3.client('elbv2')
                      
                      # Get the ALB ARN from environment or discover it
                      app_name = os.environ.get('APP_NAME')
                      env_name = os.environ.get('ENV_NAME')
                      
                      # Find the load balancer for this environment
                      response = elb.describe_load_balancers()
                      lb_arn = None
                      
                      for lb in response['LoadBalancers']:
                          # Match by tags or name pattern
                          tags_response = elb.describe_tags(ResourceArns=[lb['LoadBalancerArn']])
                          tags = {tag['Key']: tag['Value'] for tag in tags_response['TagDescriptions'][0]['Tags']}
                          
                          if (tags.get('copilot-application') == app_name and 
                              tags.get('copilot-environment') == env_name):
                              lb_arn = lb['LoadBalancerArn']
                              break
                      
                      if not lb_arn:
                          raise Exception(f"Could not find ALB for app={app_name}, env={env_name}")
                      
                      print(f"Modifying ALB: {lb_arn}")
                      
                      # Set idle timeout to 600 seconds (10 minutes) for SSE connections
                      elb.modify_load_balancer_attributes(
                          LoadBalancerArn=lb_arn,
                          Attributes=[
                              {
                                  'Key': 'idle_timeout.timeout_seconds',
                                  'Value': '600'  # 10 minutes
                              },
                          ]
                      )
                      
                      print(f"Successfully set ALB idle timeout to 600 seconds")
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                          'LoadBalancerArn': lb_arn,
                          'IdleTimeout': '600'
                      }, physicalResourceId=lb_arn)
                  
                  elif event['RequestType'] == 'Delete':
                      # No cleanup needed - use stable physical resource ID
                      physical_id = event.get('PhysicalResourceId', context.log_stream_name)
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, physicalResourceId=physical_id)
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  import traceback
                  traceback.print_exc()
                  # Use existing physical resource ID if available, otherwise use log stream name
                  physical_id = event.get('PhysicalResourceId', context.log_stream_name)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {
                      'Error': str(e)
                  }, physicalResourceId=physical_id)
      Environment:
        Variables:
          APP_NAME: !Ref App
          ENV_NAME: !Ref Env

  # IAM role for the Lambda function
  ALBTimeoutFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ModifyALBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeTags
                Resource: '*'

  # Custom resource that triggers the Lambda function
  ALBIdleTimeoutModifier:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ALBTimeoutFunction.Arn
      # Trigger update when these change
      AppName: !Ref App
      EnvName: !Ref Env
      ServiceName: !Ref Name

Outputs:
  ALBIdleTimeoutConfigured:
    Description: "ALB Idle Timeout configured for SSE connections"
    Value: "600 seconds (10 minutes)"
  FunctionArn:
    Description: "Lambda function ARN for ALB timeout configuration"
    Value: !GetAtt ALBTimeoutFunction.Arn
